const express = require('express')

function respondJSON(res,data){
  res.setHeader("Content-Type", "application/json")
  res.end(JSON.stringify(data))
}


/*================================================================================
  App setup
================================================================================*/
const app = express()

app.use((req, res, next) => {
  res.header("Access-Control-Allow-Origin", "*")
  res.header("Access-Control-Allow-Headers", "Origin, X-Requested-With, Content-Type, Accept")
  next()
})


let data =[
  {
    "Montants": "CHF 200.00",
    "id": 932,
    "Civilité": "Mr.",
    "Prénom": "Glass",
    "Nom": "Stephen",
    "Entreprise": "Inspired Developments (NSW)",
    "Adresse": "916 Barrenjoey Rd.",
    "NPA": 2108,
    "Localité": "Palm Beach",
    "Province": "NSW",
    "Pays": "Australia",
    "Téléphone": 448958600,
    "Mobile": 448958600,
    "Email": "stevejglass1@gmail.com",
    "Catégorie": "Aucune",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Daily Pass. Thursday 8 June (1x)",
    "Code Promo": "",
    "Detail": "1x Daily Pass. Thursday 8 June = 200",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 500.00",
    "id": 990,
    "Civilité": "Mrs.",
    "Prénom": "Elena",
    "Nom": "Trichina",
    "Entreprise": "Rambus Cryptography Research",
    "Adresse": "425 Market Street, 11th Floor",
    "NPA": 94105,
    "Localité": "San Francisco",
    "Province": "CA",
    "Pays": "United States",
    "Téléphone": "415-397-0123",
    "Mobile": "",
    "Email": "rchenette@rambus.com",
    "Catégorie": "Aucune",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 500.00",
    "id": 995,
    "Civilité": "Mr.",
    "Prénom": "Hamza",
    "Nom": "Baqua",
    "Entreprise": "easy global market",
    "Adresse": "1200 route des lucioles",
    "NPA": "Valbonne",
    "Localité": 6560,
    "Province": "Paca",
    "Pays": "France",
    "Téléphone": 33700000000,
    "Mobile": "",
    "Email": "hamza.baqua@eglobalmark.com",
    "Catégorie": "SME",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 500.00",
    "id": 996,
    "Civilité": "Professor",
    "Prénom": "Shuo-Yan",
    "Nom": "Chou",
    "Entreprise": "",
    "Adresse": "43 Keelung Road, Section 4",
    "NPA": 106,
    "Localité": "Taipei",
    "Province": "Taiwan",
    "Pays": "Taiwan, Province of China",
    "Téléphone": 886000000000,
    "Mobile": "",
    "Email": "sychou@mail.ntust.edu.tw",
    "Catégorie": "Academia",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 500.00",
    "id": 1003,
    "Civilité": "Dr.",
    "Prénom": "David",
    "Nom": "Lou",
    "Entreprise": "Huawei",
    "Adresse": "Riesstrasse 25",
    "NPA": 80992,
    "Localité": "Munich",
    "Province": "",
    "Pays": "Germany",
    "Téléphone": 492000000000,
    "Mobile": "",
    "Email": "zhe.lou@huawei.com",
    "Catégorie": "Industry",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 500.00",
    "id": 1029,
    "Civilité": "Mr.",
    "Prénom": "Webb",
    "Nom": "James",
    "Entreprise": "West Texas A&M University",
    "Adresse": "WTAMU Box 60811",
    "NPA": 79016,
    "Localité": "Canyon",
    "Province": "Texas",
    "Pays": "United States",
    "Téléphone": 8066511246,
    "Mobile": 8062901423,
    "Email": "jwebb@wtamu.edu",
    "Catégorie": "Academia",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 450.00",
    "id": 1030,
    "Civilité": "Mr.",
    "Prénom": "Jeon",
    "Nom": "Dongho (David)",
    "Entreprise": "NSR",
    "Adresse": "1559, Yuseong-daero",
    "NPA": "Yuseong-gu",
    "Localité": "Daejeon",
    "Province": "??",
    "Pays": "Korea, Republic of",
    "Téléphone": 428704842,
    "Mobile": "",
    "Email": "plutonic@nsr.re.kr",
    "Catégorie": "Other",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 500.00",
    "id": 1031,
    "Civilité": "Dr.",
    "Prénom": "Gilles",
    "Nom": "Thonet",
    "Entreprise": "IEC",
    "Adresse": "Rue de Varembé 3",
    "NPA": 1202,
    "Localité": "Geneva",
    "Province": "",
    "Pays": "Switzerland",
    "Téléphone": 41229190222,
    "Mobile": "",
    "Email": "gth@iec.ch",
    "Catégorie": "Other",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 450.00",
    "id": 1032,
    "Civilité": "Mr.",
    "Prénom": "Fred",
    "Nom": "Herren",
    "Entreprise": "SGS",
    "Adresse": "Place des Alpes 1",
    "NPA": 1201,
    "Localité": "Geneva",
    "Province": "",
    "Pays": "Switzerland",
    "Téléphone": 227399254,
    "Mobile": "",
    "Email": "fred.herren@sgs.com",
    "Catégorie": "Aucune",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 450.00",
    "id": 1037,
    "Civilité": "Professor",
    "Prénom": "Yun",
    "Nom": "KS",
    "Entreprise": "",
    "Adresse": "35 Baekbeom-ro, Mapo-gu",
    "NPA": 4107,
    "Localité": "Seoul",
    "Province": "",
    "Pays": "Korea, Republic of",
    "Téléphone": -9540,
    "Mobile": "",
    "Email": "ksyun@sogang.ac.kr",
    "Catégorie": "Aucune",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 450.00",
    "id": 1045,
    "Civilité": "Mr.",
    "Prénom": "Zsolt",
    "Nom": "Kasza",
    "Entreprise": "Exxonmobil BSC Hungary",
    "Adresse": "Váci str 81-85,",
    "NPA": 1139,
    "Localité": "Budapest",
    "Province": "",
    "Pays": "Hungary",
    "Téléphone": 3612985820,
    "Mobile": 36306764728,
    "Email": "zsolt.kasza@exxonmobil.com",
    "Catégorie": "Industry",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 500.00",
    "id": 1046,
    "Civilité": "Mrs.",
    "Prénom": "Kristian",
    "Nom": "Di Gaetano",
    "Entreprise": "Accenture",
    "Adresse": "7802 Montane Run Court",
    "NPA": "Waxhaw",
    "Localité": 28173,
    "Province": "NC",
    "Pays": "United States",
    "Téléphone": 7043326411,
    "Mobile": 9802304109,
    "Email": "kristian.digaetano@accenture.com",
    "Catégorie": "Aucune",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 450.00",
    "id": 1054,
    "Civilité": "Mr.",
    "Prénom": "Fred",
    "Nom": "Herren",
    "Entreprise": "SGS",
    "Adresse": "Place des Alpes 1",
    "NPA": 1201,
    "Localité": "Geneva",
    "Province": "",
    "Pays": "Switzerland",
    "Téléphone": 227399254,
    "Mobile": "",
    "Email": "laure.cocoual@sgs.com",
    "Catégorie": "Aucune",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 450.00",
    "id": 1060,
    "Civilité": "Mr.",
    "Prénom": "Bernhard",
    "Nom": "Solomita",
    "Entreprise": "OFCOM Switzerland",
    "Adresse": "Zukunftstrasse 44",
    "NPA": 2501,
    "Localité": "Biel/Bienne",
    "Province": "",
    "Pays": "Switzerland",
    "Téléphone": "+41 58 460 5742",
    "Mobile": "",
    "Email": "bernhard.solomita@bakom.admin.ch",
    "Catégorie": "Public administration",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 450.00",
    "id": 1061,
    "Civilité": "Mr.",
    "Prénom": "Halff",
    "Nom": "Larry",
    "Entreprise": "Bright/Contrast LLC",
    "Adresse": "26 Allston Way",
    "NPA": 94127,
    "Localité": "San Francisco",
    "Province": "CA",
    "Pays": "United States",
    "Téléphone": 14155470370,
    "Mobile": 14153414478,
    "Email": "larry@brightcontrast.com",
    "Catégorie": "Industry",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 450.00",
    "id": 1105,
    "Civilité": "Mr.",
    "Prénom": "Félicien",
    "Nom": "Fleury",
    "Entreprise": "NGSENS",
    "Adresse": "Route de Florissant 6",
    "NPA": 1206,
    "Localité": "Genève",
    "Province": "",
    "Pays": "Geneve",
    "Téléphone": "0041 22 552 09 36",
    "Mobile": "",
    "Email": "felicien.fleury@ngsens.com",
    "Catégorie": "Industry",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 500.00",
    "id": 1109,
    "Civilité": "Mr.",
    "Prénom": "Ad",
    "Nom": "ten Berg",
    "Entreprise": "ARTEMIS-IA",
    "Adresse": "High Tech Campus 69-3",
    "NPA": "Eindhoven",
    "Localité": "5656 AG",
    "Province": "The Netherlands",
    "Pays": "Netherlands",
    "Téléphone": 31880036188,
    "Mobile": "",
    "Email": "ad.ten.berg@artemis-ia.eu",
    "Catégorie": "Other",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 500.00",
    "id": 1110,
    "Civilité": "Mrs.",
    "Prénom": "Chantal",
    "Nom": "Schoen",
    "Entreprise": "ARTEMIS-IA",
    "Adresse": "High Tech Campus 69-3",
    "NPA": "Eindhoven",
    "Localité": "5656 AG",
    "Province": "Netherlands",
    "Pays": "Netherlands",
    "Téléphone": 31880036188,
    "Mobile": "",
    "Email": "chantal.schoen@artemis-ia.eu",
    "Catégorie": "Aucune",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Full Registration incl. Gala Dinner (1x)",
    "Code Promo": "",
    "Detail": "1x Full Registration incl. Gala Dinner = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": 1
  },
  {
    "Montants": "CHF 450.00",
    "id": 1112,
    "Civilité": "Dr.",
    "Prénom": "Raza",
    "Nom": "Shahid",
    "Entreprise": "RISE SICS",
    "Adresse": "Isafjordsgatan 22\n\n16440 KISTA\n\nStockholm",
    "NPA": 16440,
    "Localité": "Kista",
    "Province": "Stockholm",
    "Pays": "Sweden",
    "Téléphone": 46800000000,
    "Mobile": 46768831797,
    "Email": "shahid.raza@ri.se",
    "Catégorie": "Research centre",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Special Registration requiring a Code (Registration fees will be calculated after entering the code in page 3) (1x)",
    "Code Promo": "WithDinner026978 [50 CHF]",
    "Detail": "1x Special Registration requiring a Code <font style='color:red'>(Registration fees will be calculated after entering the code in page 3)</font> = 500",
    "": "#VALEUR!",
    "Gala (Code)": 1,
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 420.00",
    "id": 1128,
    "Civilité": "Dr.",
    "Prénom": "Sergio",
    "Nom": "Gusmeroli",
    "Entreprise": "Politecnico di Milano",
    "Adresse": "Piazza dei Daini 4",
    "NPA": 20126,
    "Localité": "MILANO",
    "Province": "",
    "Pays": "Italy",
    "Téléphone": 393000000000,
    "Mobile": "",
    "Email": "sergio.gusmeroli@polimi.it",
    "Catégorie": "Aucune",
    "Newsletter": "oui",
    "Association": "",
    "Remarque": "",
    "Articles": "Special Registration requiring a Code (Registration fees will be calculated after entering the code in page 3) (1x)",
    "Code Promo": "NoDinner044685 [80 CHF]",
    "Detail": "1x Special Registration requiring a Code <font style='color:red'>(Registration fees will be calculated after entering the code in page 3)</font> = 500",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 450.00",
    "id": 1143,
    "Civilité": "Mr.",
    "Prénom": "Hoang Minh",
    "Nom": "Nguyen Hoang Minh",
    "Entreprise": "Korea Advanced Institute of Science and Technology (KAIST)",
    "Adresse": "#921 N1, KAIST, 291 Daehak-ro, Yuseong-gu, Daejeon 34141, Republic of Korea",
    "NPA": 34141,
    "Localité": "Daejeon",
    "Province": "",
    "Pays": "Korea, Republic of",
    "Téléphone": 821000000000,
    "Mobile": "",
    "Email": "minhhoang@kaist.ac.kr",
    "Catégorie": "Student",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Reduced Registration (no Gala Dinner) (1x)",
    "Code Promo": "",
    "Detail": "1x Reduced Registration (no Gala Dinner) = 450",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  },
  {
    "Montants": "CHF 200.00",
    "id": 1145,
    "Civilité": "Mr.",
    "Prénom": "Alexis",
    "Nom": "Olivereau",
    "Entreprise": "List",
    "Adresse": "CEA Saclay - NanoINNOV\n\nBat 862 - PC 173",
    "NPA": 91191,
    "Localité": "Gif sur Yvette Cedex",
    "Province": "",
    "Pays": "France",
    "Téléphone": 33169089233,
    "Mobile": 33664905019,
    "Email": "alexis.olivereau@cea.fr",
    "Catégorie": "Research centre",
    "Newsletter": "non",
    "Association": "",
    "Remarque": "",
    "Articles": "Daily Pass. Thursday 8 June (1x)",
    "Code Promo": "",
    "Detail": "1x Daily Pass. Thursday 8 June = 200",
    "": "#VALEUR!",
    "Gala (Code)": "",
    "Gala (autres)": ""
  }
]

app.use('/', express.static(__dirname + '/public'))

app.get('/find',function (req, res) {
  const keys = Object.keys(req.query)
  let response = data
  if(keys.length > 0)
  	response = data.filter( entry => {
  		let ok = true
  		for(let i=0; i<keys.length;i++){
  			let key = keys[i]
  			if(!(entry[key] && entry[key].toString().toLowerCase().includes(req.query[key].toString().toLowerCase()))){
  				ok = false
  				break;
  			}
  		}
  		return ok
  	})
  respondJSON(res,response)
})

const server = app.listen(6969, () => {
  let host = server.address().address
  let port = server.address().port
  console.log("Search server running at http://%s:%s", host, port)
})